// Class: ReadMLPD
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPD
TMVA Release   : 4.0.3         [262147]
ROOT Release   : 5.26/00       [334336]
Creator        : michael
Date           : Thu Aug  5 15:22:53 2010
Host           : Darwin dhcp222.iihe.ac.be 9.8.0 Darwin Kernel Version 9.8.0: Wed Jul 15 16:55:01 PDT 2009; root:xnu-1228.15.4~1/RELEASE_I386 i386
Dir            : /Users/michael/Documents/doctoraat/JESanalysis/TopTreeAnalysis/macros
Training events: 223104
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Decorrelate" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "0.000000e+00" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
btag                          btag                          btag                          btag                                                            'F'    [0,0.999998986721]
ThPtOverSumPt                 ThPtOverSumPt                 ThPtOverSumPt                 ThPtOverSumPt                                                   'F'    [0,0.68992036581]
AngleThWh                     AngleThWh                     AngleThWh                     AngleThWh                                                       'F'    [0,3.10163426399]
AngleBlMu                     AngleBlMu                     AngleBlMu                     AngleBlMu                                                       'F'    [0,3.10783958435]
AngleThBl                     AngleThBl                     AngleThBl                     AngleThBl                                                       'F'    [0,3.12073779106]
AngleThBh                     AngleThBh                     AngleThBh                     AngleThBh                                                       'F'    [0,3.06374049187]
AngleThMu                     AngleThMu                     AngleThMu                     AngleThMu                                                       'F'    [0,3.12847614288]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadMLPD : public IClassifierReader {

 public:

   // constructor
   ReadMLPD( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPD" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "btag", "ThPtOverSumPt", "AngleThWh", "AngleBlMu", "AngleThBl", "AngleThBh", "AngleThMu" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -0.294300079345703;
      fVmax[0] = 4.02233505249023;
      fVmin[1] = -0.611135363578796;
      fVmax[1] = 7.17640399932861;
      fVmin[2] = -0.729874730110168;
      fVmax[2] = 6.74808597564697;
      fVmin[3] = -0.794734835624695;
      fVmax[3] = 4.72484540939331;
      fVmin[4] = -0.840423226356506;
      fVmax[4] = 4.27162742614746;
      fVmin[5] = -0.545158743858337;
      fVmax[5] = 5.06633806228638;
      fVmin[6] = -0.973435819149017;
      fVmax[6] = 4.14592123031616;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPD() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fDecTF_1[3][7][7];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[8][8];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][8];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPD::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 8; fWeights[0] = new double[8]; 
   fLayerSize[1] = 8; fWeights[1] = new double[8]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.823611859713766;
   fWeightMatrix0to1[1][0] = -0.873507347617564;
   fWeightMatrix0to1[2][0] = 0.00789868422819132;
   fWeightMatrix0to1[3][0] = -3.19680811390385;
   fWeightMatrix0to1[4][0] = 0.752818282448771;
   fWeightMatrix0to1[5][0] = -0.512179871423412;
   fWeightMatrix0to1[6][0] = -0.967349512617915;
   fWeightMatrix0to1[0][1] = -0.123455775709701;
   fWeightMatrix0to1[1][1] = 0.183250256500528;
   fWeightMatrix0to1[2][1] = -0.177737405237699;
   fWeightMatrix0to1[3][1] = -0.0433504418605224;
   fWeightMatrix0to1[4][1] = 1.58843967143694;
   fWeightMatrix0to1[5][1] = 0.0125351166711353;
   fWeightMatrix0to1[6][1] = -0.551552599569581;
   fWeightMatrix0to1[0][2] = -1.54229338500169;
   fWeightMatrix0to1[1][2] = 0.220560033688071;
   fWeightMatrix0to1[2][2] = 3.08376454102287;
   fWeightMatrix0to1[3][2] = 0.0349960260056233;
   fWeightMatrix0to1[4][2] = -0.00414557582410331;
   fWeightMatrix0to1[5][2] = -2.90708731257953;
   fWeightMatrix0to1[6][2] = 0.493106593862089;
   fWeightMatrix0to1[0][3] = 0.00877649703453868;
   fWeightMatrix0to1[1][3] = -1.80280741241868;
   fWeightMatrix0to1[2][3] = 1.10482118891546;
   fWeightMatrix0to1[3][3] = 0.423774423826215;
   fWeightMatrix0to1[4][3] = 0.668718963315937;
   fWeightMatrix0to1[5][3] = -0.793971743200351;
   fWeightMatrix0to1[6][3] = 0.744862254719049;
   fWeightMatrix0to1[0][4] = -1.05676327328037;
   fWeightMatrix0to1[1][4] = -0.995790158333094;
   fWeightMatrix0to1[2][4] = 0.264691780594714;
   fWeightMatrix0to1[3][4] = -0.58419933507258;
   fWeightMatrix0to1[4][4] = 2.06931045152973;
   fWeightMatrix0to1[5][4] = -0.54286358009587;
   fWeightMatrix0to1[6][4] = -0.274984478748904;
   fWeightMatrix0to1[0][5] = -0.487009583571412;
   fWeightMatrix0to1[1][5] = -0.0776084917715237;
   fWeightMatrix0to1[2][5] = 1.67217411978744;
   fWeightMatrix0to1[3][5] = 0.391155054826866;
   fWeightMatrix0to1[4][5] = -0.0948418953592721;
   fWeightMatrix0to1[5][5] = -1.64853545004539;
   fWeightMatrix0to1[6][5] = 0.423901707746634;
   fWeightMatrix0to1[0][6] = 0.0449858854246104;
   fWeightMatrix0to1[1][6] = -1.86651997816328;
   fWeightMatrix0to1[2][6] = 0.383185891681783;
   fWeightMatrix0to1[3][6] = 0.0395824245739454;
   fWeightMatrix0to1[4][6] = 1.38841658828672;
   fWeightMatrix0to1[5][6] = -0.482399694760523;
   fWeightMatrix0to1[6][6] = -0.326892315236845;
   fWeightMatrix0to1[0][7] = -1.52540217139089;
   fWeightMatrix0to1[1][7] = 1.17855019264554;
   fWeightMatrix0to1[2][7] = -1.08372631951411;
   fWeightMatrix0to1[3][7] = 2.68798633440415;
   fWeightMatrix0to1[4][7] = 2.37446635377027;
   fWeightMatrix0to1[5][7] = 1.00590082316155;
   fWeightMatrix0to1[6][7] = 3.86182698825799;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.37158295820349;
   fWeightMatrix1to2[0][1] = -0.047434019277744;
   fWeightMatrix1to2[0][2] = 0.993294234680145;
   fWeightMatrix1to2[0][3] = -0.10957396998809;
   fWeightMatrix1to2[0][4] = 1.11491242301501;
   fWeightMatrix1to2[0][5] = 1.31258701023499;
   fWeightMatrix1to2[0][6] = -0.891211816910159;
   fWeightMatrix1to2[0][7] = -1.10910141554525;
}

inline double ReadMLPD::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
   }

   return fWeights[2][0];
}

double ReadMLPD::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLPD::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPD::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPD::InitTransform_1()
{
   fDecTF_1[0][0][0] = 2.84368140913;
   fDecTF_1[0][0][1] = -0.0594550398114;
   fDecTF_1[0][0][2] = -0.0308314962435;
   fDecTF_1[0][0][3] = 0.00188283962881;
   fDecTF_1[0][0][4] = 0.00677897771362;
   fDecTF_1[0][0][5] = -0.00553493413746;
   fDecTF_1[0][0][6] = 0.0164515075006;
   fDecTF_1[0][1][0] = -0.0594550398114;
   fDecTF_1[0][1][1] = 8.96669499707;
   fDecTF_1[0][1][2] = 0.598141960684;
   fDecTF_1[0][1][3] = 0.3495484838;
   fDecTF_1[0][1][4] = -0.264674313092;
   fDecTF_1[0][1][5] = 0.193082893235;
   fDecTF_1[0][1][6] = -0.0008136804282;
   fDecTF_1[0][2][0] = -0.0308314962435;
   fDecTF_1[0][2][1] = 0.598141960684;
   fDecTF_1[0][2][2] = 2.57757215561;
   fDecTF_1[0][2][3] = -0.0971328703509;
   fDecTF_1[0][2][4] = -0.0588649729461;
   fDecTF_1[0][2][5] = 0.108961191782;
   fDecTF_1[0][2][6] = -0.0183013048524;
   fDecTF_1[0][3][0] = 0.00188283962881;
   fDecTF_1[0][3][1] = 0.3495484838;
   fDecTF_1[0][3][2] = -0.0971328703509;
   fDecTF_1[0][3][3] = 1.67678224697;
   fDecTF_1[0][3][4] = -0.0364288367876;
   fDecTF_1[0][3][5] = -0.0587593169996;
   fDecTF_1[0][3][6] = 0.0261174768948;
   fDecTF_1[0][4][0] = 0.00677897771362;
   fDecTF_1[0][4][1] = -0.264674313092;
   fDecTF_1[0][4][2] = -0.0588649729461;
   fDecTF_1[0][4][3] = -0.0364288367876;
   fDecTF_1[0][4][4] = 1.49676047925;
   fDecTF_1[0][4][5] = -0.0631906867005;
   fDecTF_1[0][4][6] = -0.230159529747;
   fDecTF_1[0][5][0] = -0.00553493413746;
   fDecTF_1[0][5][1] = 0.193082893235;
   fDecTF_1[0][5][2] = 0.108961191782;
   fDecTF_1[0][5][3] = -0.0587593169996;
   fDecTF_1[0][5][4] = -0.0631906867005;
   fDecTF_1[0][5][5] = 1.92990361769;
   fDecTF_1[0][5][6] = -0.0250160919845;
   fDecTF_1[0][6][0] = 0.0164515075006;
   fDecTF_1[0][6][1] = -0.0008136804282;
   fDecTF_1[0][6][2] = -0.0183013048524;
   fDecTF_1[0][6][3] = 0.0261174768948;
   fDecTF_1[0][6][4] = -0.230159529747;
   fDecTF_1[0][6][5] = -0.0250160919845;
   fDecTF_1[0][6][6] = 1.46590498282;
   fDecTF_1[1][0][0] = 4.53713478626;
   fDecTF_1[1][0][1] = -0.0556205717186;
   fDecTF_1[1][0][2] = -0.0217508721697;
   fDecTF_1[1][0][3] = 0.0115774703133;
   fDecTF_1[1][0][4] = -0.00185521712395;
   fDecTF_1[1][0][5] = -0.000328043761718;
   fDecTF_1[1][0][6] = 0.00864708301048;
   fDecTF_1[1][1][0] = -0.0556205717186;
   fDecTF_1[1][1][1] = 9.51858739337;
   fDecTF_1[1][1][2] = 0.405683564858;
   fDecTF_1[1][1][3] = 0.310428702977;
   fDecTF_1[1][1][4] = -0.269882870961;
   fDecTF_1[1][1][5] = 0.00354101235037;
   fDecTF_1[1][1][6] = -0.112791179627;
   fDecTF_1[1][2][0] = -0.0217508721697;
   fDecTF_1[1][2][1] = 0.405683564858;
   fDecTF_1[1][2][2] = 2.20097944298;
   fDecTF_1[1][2][3] = -0.127720073832;
   fDecTF_1[1][2][4] = -0.185670990182;
   fDecTF_1[1][2][5] = 0.0708340037834;
   fDecTF_1[1][2][6] = -0.0517915779208;
   fDecTF_1[1][3][0] = 0.0115774703133;
   fDecTF_1[1][3][1] = 0.310428702977;
   fDecTF_1[1][3][2] = -0.127720073832;
   fDecTF_1[1][3][3] = 1.56820948433;
   fDecTF_1[1][3][4] = -0.0182699491087;
   fDecTF_1[1][3][5] = -0.101622264407;
   fDecTF_1[1][3][6] = -0.255634538296;
   fDecTF_1[1][4][0] = -0.00185521712395;
   fDecTF_1[1][4][1] = -0.269882870961;
   fDecTF_1[1][4][2] = -0.185670990182;
   fDecTF_1[1][4][3] = -0.0182699491087;
   fDecTF_1[1][4][4] = 1.47137068165;
   fDecTF_1[1][4][5] = -0.122090895491;
   fDecTF_1[1][4][6] = -0.0769233208145;
   fDecTF_1[1][5][0] = -0.000328043761718;
   fDecTF_1[1][5][1] = 0.00354101235037;
   fDecTF_1[1][5][2] = 0.0708340037834;
   fDecTF_1[1][5][3] = -0.101622264407;
   fDecTF_1[1][5][4] = -0.122090895491;
   fDecTF_1[1][5][5] = 1.70053819576;
   fDecTF_1[1][5][6] = -0.0155452680162;
   fDecTF_1[1][6][0] = 0.00864708301048;
   fDecTF_1[1][6][1] = -0.112791179627;
   fDecTF_1[1][6][2] = -0.0517915779208;
   fDecTF_1[1][6][3] = -0.255634538296;
   fDecTF_1[1][6][4] = -0.0769233208145;
   fDecTF_1[1][6][5] = -0.0155452680162;
   fDecTF_1[1][6][6] = 1.44850146253;
   fDecTF_1[2][0][0] = 3.93214650366;
   fDecTF_1[2][0][1] = -0.193169286121;
   fDecTF_1[2][0][2] = -0.0047941369697;
   fDecTF_1[2][0][3] = 0.0673603168658;
   fDecTF_1[2][0][4] = -0.0494544808154;
   fDecTF_1[2][0][5] = 0.019390536474;
   fDecTF_1[2][0][6] = -0.0280244021897;
   fDecTF_1[2][1][0] = -0.193169286121;
   fDecTF_1[2][1][1] = 9.38978182186;
   fDecTF_1[2][1][2] = 0.422189893163;
   fDecTF_1[2][1][3] = 0.328354626725;
   fDecTF_1[2][1][4] = -0.285639215248;
   fDecTF_1[2][1][5] = 0.0237897930021;
   fDecTF_1[2][1][6] = -0.117536756306;
   fDecTF_1[2][2][0] = -0.0047941369697;
   fDecTF_1[2][2][1] = 0.422189893163;
   fDecTF_1[2][2][2] = 2.22251542624;
   fDecTF_1[2][2][3] = -0.131457602532;
   fDecTF_1[2][2][4] = -0.172918578262;
   fDecTF_1[2][2][5] = 0.0705761555835;
   fDecTF_1[2][2][6] = -0.0459955137639;
   fDecTF_1[2][3][0] = 0.0673603168658;
   fDecTF_1[2][3][1] = 0.328354626725;
   fDecTF_1[2][3][2] = -0.131457602532;
   fDecTF_1[2][3][3] = 1.55646374736;
   fDecTF_1[2][3][4] = -0.00486234237913;
   fDecTF_1[2][3][5] = -0.103529380185;
   fDecTF_1[2][3][6] = -0.22534223304;
   fDecTF_1[2][4][0] = -0.0494544808154;
   fDecTF_1[2][4][1] = -0.285639215248;
   fDecTF_1[2][4][2] = -0.172918578262;
   fDecTF_1[2][4][3] = -0.00486234237913;
   fDecTF_1[2][4][4] = 1.46074978469;
   fDecTF_1[2][4][5] = -0.114125309667;
   fDecTF_1[2][4][6] = -0.0967797197163;
   fDecTF_1[2][5][0] = 0.019390536474;
   fDecTF_1[2][5][1] = 0.0237897930021;
   fDecTF_1[2][5][2] = 0.0705761555835;
   fDecTF_1[2][5][3] = -0.103529380185;
   fDecTF_1[2][5][4] = -0.114125309667;
   fDecTF_1[2][5][5] = 1.71429393715;
   fDecTF_1[2][5][6] = -0.0135001994115;
   fDecTF_1[2][6][0] = -0.0280244021897;
   fDecTF_1[2][6][1] = -0.117536756306;
   fDecTF_1[2][6][2] = -0.0459955137639;
   fDecTF_1[2][6][3] = -0.22534223304;
   fDecTF_1[2][6][4] = -0.0967797197163;
   fDecTF_1[2][6][5] = -0.0135001994115;
   fDecTF_1[2][6][6] = 1.43773415909;
}

//_______________________________________________________________________
inline void ReadMLPD::Transform_1( std::vector<double>& iv, int cls) const
{
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }
   std::vector<double> tv;
   for (int i=0; i<7;i++) {
      double v = 0;
      for (int j=0; j<7; j++)
         v += iv[j] * fDecTF_1[cls][i][j];
      tv.push_back(v);
   }
   for (int i=0; i<7;i++) iv[i] = tv[i];
}

//_______________________________________________________________________
inline void ReadMLPD::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPD::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
