// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.0.3         [262147]
ROOT Release   : 5.26/00       [334336]
Creator        : michael
Date           : Thu Aug  5 15:02:21 2010
Host           : Darwin dhcp222.iihe.ac.be 9.8.0 Darwin Kernel Version 9.8.0: Wed Jul 15 16:55:01 PDT 2009; root:xnu-1228.15.4~1/RELEASE_I386 i386
Dir            : /Users/michael/Documents/doctoraat/JESanalysis/TopTreeAnalysis/macros
Training events: 223104
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "0.000000e+00" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
btag                          btag                          btag                          btag                                                            'F'    [0,0.999998986721]
ThPtOverSumPt                 ThPtOverSumPt                 ThPtOverSumPt                 ThPtOverSumPt                                                   'F'    [0,0.68992036581]
AngleThWh                     AngleThWh                     AngleThWh                     AngleThWh                                                       'F'    [0,3.10163426399]
AngleBlMu                     AngleBlMu                     AngleBlMu                     AngleBlMu                                                       'F'    [0,3.10783958435]
AngleThBl                     AngleThBl                     AngleThBl                     AngleThBl                                                       'F'    [0,3.12073779106]
AngleThBh                     AngleThBh                     AngleThBh                     AngleThBh                                                       'F'    [0,3.06374049187]
AngleThMu                     AngleThMu                     AngleThMu                     AngleThMu                                                       'F'    [0,3.12847614288]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "btag", "ThPtOverSumPt", "AngleThWh", "AngleBlMu", "AngleThBl", "AngleThBh", "AngleThMu" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][7];
   double fMax_1[3][7];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[8][8];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][8];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 8; fWeights[0] = new double[8]; 
   fLayerSize[1] = 8; fWeights[1] = new double[8]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 1.42794915880567;
   fWeightMatrix0to1[1][0] = -1.01186257289025;
   fWeightMatrix0to1[2][0] = 1.64114802650932;
   fWeightMatrix0to1[3][0] = -1.16220169706562;
   fWeightMatrix0to1[4][0] = 1.92381934458616;
   fWeightMatrix0to1[5][0] = 1.39285141133898;
   fWeightMatrix0to1[6][0] = 1.42653037006758;
   fWeightMatrix0to1[0][1] = 1.13112509725606;
   fWeightMatrix0to1[1][1] = 1.17144942366602;
   fWeightMatrix0to1[2][1] = 1.21977542059887;
   fWeightMatrix0to1[3][1] = 0.660848171938113;
   fWeightMatrix0to1[4][1] = 1.3509590157807;
   fWeightMatrix0to1[5][1] = 0.871173681733179;
   fWeightMatrix0to1[6][1] = 1.39501502456284;
   fWeightMatrix0to1[0][2] = 0.755714762137946;
   fWeightMatrix0to1[1][2] = 1.80469194369047;
   fWeightMatrix0to1[2][2] = -0.356040662242626;
   fWeightMatrix0to1[3][2] = 2.46807639325807;
   fWeightMatrix0to1[4][2] = 1.88508974342971;
   fWeightMatrix0to1[5][2] = -0.636791258133265;
   fWeightMatrix0to1[6][2] = 1.08932365480633;
   fWeightMatrix0to1[0][3] = -4.16786178388145;
   fWeightMatrix0to1[1][3] = -0.694815775878357;
   fWeightMatrix0to1[2][3] = -0.596918038205447;
   fWeightMatrix0to1[3][3] = 0.0255171698085337;
   fWeightMatrix0to1[4][3] = -0.29896122429017;
   fWeightMatrix0to1[5][3] = -3.03395124706935;
   fWeightMatrix0to1[6][3] = -0.892507951911845;
   fWeightMatrix0to1[0][4] = -1.30395217667486;
   fWeightMatrix0to1[1][4] = 1.43369781037878;
   fWeightMatrix0to1[2][4] = 1.57283310364847;
   fWeightMatrix0to1[3][4] = 1.43478866528418;
   fWeightMatrix0to1[4][4] = 1.86936574574197;
   fWeightMatrix0to1[5][4] = 0.43497311855801;
   fWeightMatrix0to1[6][4] = 1.425195238033;
   fWeightMatrix0to1[0][5] = -1.04533628890493;
   fWeightMatrix0to1[1][5] = 0.797305716644847;
   fWeightMatrix0to1[2][5] = 0.220675564933191;
   fWeightMatrix0to1[3][5] = 1.54440934274987;
   fWeightMatrix0to1[4][5] = 1.32091903178232;
   fWeightMatrix0to1[5][5] = -1.11376299112675;
   fWeightMatrix0to1[6][5] = 0.345161665695746;
   fWeightMatrix0to1[0][6] = 1.78874250386366;
   fWeightMatrix0to1[1][6] = 0.133538254399303;
   fWeightMatrix0to1[2][6] = -0.22822236198315;
   fWeightMatrix0to1[3][6] = -0.0578960573300763;
   fWeightMatrix0to1[4][6] = 0.0960018694207194;
   fWeightMatrix0to1[5][6] = 0.143397024662146;
   fWeightMatrix0to1[6][6] = 0.275764588710242;
   fWeightMatrix0to1[0][7] = -4.06340390614144;
   fWeightMatrix0to1[1][7] = -1.70294102178683;
   fWeightMatrix0to1[2][7] = -3.63592249751828;
   fWeightMatrix0to1[3][7] = -2.84156324140867;
   fWeightMatrix0to1[4][7] = -0.580359590171882;
   fWeightMatrix0to1[5][7] = -4.79357390585415;
   fWeightMatrix0to1[6][7] = -0.0784162081611606;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.02823596096993;
   fWeightMatrix1to2[0][1] = -0.988982265295619;
   fWeightMatrix1to2[0][2] = 2.07452779217244;
   fWeightMatrix1to2[0][3] = 1.03697049286005;
   fWeightMatrix1to2[0][4] = -1.14596724937206;
   fWeightMatrix1to2[0][5] = -1.60149576147066;
   fWeightMatrix1to2[0][6] = 1.1956915596202;
   fWeightMatrix1to2[0][7] = 0.000220221283657224;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 0.999998986721;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 0.999998986721;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 0.999998986721;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 0.68992036581;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 0.68992036581;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 0.68992036581;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 2.81187844276;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 3.10163426399;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 3.10163426399;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 3.09665584564;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 3.10783958435;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 3.10783958435;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 3.08718323708;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 3.12073779106;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 3.12073779106;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 2.90224647522;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 3.06374049187;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 3.06374049187;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 3.10696482658;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 3.12847614288;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 3.12847614288;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
   else cls = 2;
}
   for (int ivar=0;ivar<7;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[ivar] = (iv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
